config/routes.rb
Rails.application.routes.draw do
  root to: "rooms#index"
  resources :rooms
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/place.rb
class Place < ApplicationRecord
  belongs_to :room, optional: true
end

app/models/room.rb
class Room < ApplicationRecord
  validates :name, presence:true
  validates :price, presence:true
  validates :address, presence:true
  validates :age, presence:true
  validates :comment, presence:true
  has_many :places,dependent: :destroy
  accepts_nested_attributes_for :places
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action:set_room,only:[:edit,:update,:show,:destroy]
  def index
    @rooms = Room.all
  end

  def new
    @room = Room.new
    2.times{@room.places.build}
  end

  def create
    @room = Room.new(room_params)
    if @room.save
      redirect_to rooms_path,notice:"登録しました"
    else
      render 'new'
    end
  end

  def show
  end

  def edit
  end

  def update
    if @room.update(room_params)
      redirect_to rooms_path,notice:"編集しました"
    else
      render 'edit'
    end
  end

  def destroy
    @room.delete
    redirect_to rooms_path,notice:"削除しました"
  end

  private

  def room_params
    params.require(:room).permit(:name,:price,:address,:age,:comment,
    places_attributes: [:id,:room_id,:train,:station,:walk])
  end

  def set_room
    @room = Room.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DevExam</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= flash[:notice] %>
    <%= yield %>
  </body>
</html>

app/views/rooms/_form.html.erb
<% @room.errors.full_messages.each do |msg| %>
  <div><%= msg %></div>
<% end %>
    <%= form_for @room do |f| %>
    <div class = under_line>
        <li><%= f.label :物件名 %></li>
        <li><%= f.text_field :name %></li>

        <li><%= f.label :賃料 %></li>
        <li><%= f.text_field :price %>円</li>

        <li><%= f.label :住所 %></li>
        <li><%= f.text_field :address %></li>

        <li><%= f.label :築年数 %></li>
        <li><%= f.text_field :age %>年</li>

        <li><%= f.label :備考 %></li>
        <li><%= f.text_area :comment %></li>
    </div>

        <%= f.fields_for :places do |p| %>
            <h3>最寄り駅<%= p.index + 1 %></h3>
            <li><%= p.label :路線名 %></li>
            <li><%= p.text_field :train %></li>

            <li><%= p.label :駅名 %></li>
            <li><%= p.text_field :station %></li>

            <li><%= p.label :徒歩分数 %></li>
            <li><%= p.text_field :walk %>分</li>
        <% end %>
        <li><%= f.submit %></li>
      <% end %>

app/views/rooms/edit.html.erb
  <h2>物件編集</h2>
    <%= render 'form' %>
      <div>
        <a><%= link_to "詳細",room_path(@room.id) %></a>
        <a class = "line"><%= link_to "戻る", :back %></a>
      </div>

app/views/rooms/index.html.erb
<h1>物件一覧</h1>
  <table>
    <tr>
      <th>物件名</th>
      <th>賃料</th>
      <th>住所</th>
      <th>築年数</th>
      <th>備考</th>
    </tr>
    <% @rooms.each do |room| %>
      <tr>
        <td><%= room.name %></td>
        <td><%= room.price %>円</td>
        <td><%= room.address %></td>
        <td><%= room.age %>年</td>
        <td><%= room.comment %></td>
        <td><%= link_to "詳細",room_path(room.id) %></td>
        <td><%= link_to "編集",edit_room_path(room.id) %></td>
        <td><%= link_to "削除",room_path(room.id), method: :delete %></td>
      </tr>
    <% end %>
  </table>
  <%= link_to "物件を登録する",new_room_path %>

app/views/rooms/new.html.erb
  <h1>登録</h1>
    <%= render 'form' %>
    <%= link_to "戻る", rooms_path %>

app/views/rooms/show.html.erb
  <div class = under_line>
  <table>
    <tr><th>物件名:</th><td><%= @room.name %></td></tr>
    <tr><th>賃料:</th><td><%=  @room.price %>円</td></tr>
    <tr><th>住所:</th><td><%=  @room.address %></td></tr>
    <tr><th>築年数:</th><td><%= @room.age %>年</td></tr>
    <tr><th>備考:</th><td><%= @room.comment %></td></tr>
  </table>
  </div>
  <% @room.places.each_with_index do |place,number| %>
    <h3>最寄り駅<%= number + 1 %></h3>
    <table>
      <tr><th>路線名</th><td><%= place.train %></td></tr>
      <tr><th>駅名</th><td><%= place.station %></td></tr>
      <tr><th>徒歩分数</th><td><%=  place.walk %>分</td></tr>
    </table>
  <% end %>
    <a><%= link_to "編集",edit_room_path(@room.id) %></a>
    <a class = line><%= link_to "戻る", rooms_path %></a>